//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelToUser
    {
        public string userId { get; set; }
        public int travelCode { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan hour { get; set; }
        public int boardingStation { get; set; }
        public int dropStation { get; set; }
    
        public virtual Travel Travel { get; set; }
        public virtual User User { get; set; }
    }
}
